# Generated by Django 4.1.1 on 2023-01-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lokasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_TPI", models.CharField(max_length=100)),
                ("g_lintang", models.FloatField(null=True)),
                ("g_bujur", models.FloatField(null=True)),
                (
                    "gambar",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produksi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_ikan", models.CharField(max_length=75)),
                ("tahun1", models.CharField(max_length=75)),
                ("tahun2", models.CharField(max_length=75)),
                ("analisis", models.CharField(max_length=550)),
            ],
        ),
    ]
